// Generated by gencpp from file direct_lidar_odometry/save_trajRequest.msg
// DO NOT EDIT!


#ifndef DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJREQUEST_H
#define DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace direct_lidar_odometry
{
template <class ContainerAllocator>
struct save_trajRequest_
{
  typedef save_trajRequest_<ContainerAllocator> Type;

  save_trajRequest_()
    : save_path()  {
    }
  save_trajRequest_(const ContainerAllocator& _alloc)
    : save_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _save_path_type;
  _save_path_type save_path;





  typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct save_trajRequest_

typedef ::direct_lidar_odometry::save_trajRequest_<std::allocator<void> > save_trajRequest;

typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajRequest > save_trajRequestPtr;
typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajRequest const> save_trajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator1> & lhs, const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator2> & rhs)
{
  return lhs.save_path == rhs.save_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator1> & lhs, const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace direct_lidar_odometry

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d220fdd29bb0f13aa508a49f780235bb";
  }

  static const char* value(const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd220fdd29bb0f13aULL;
  static const uint64_t static_value2 = 0xa508a49f780235bbULL;
};

template<class ContainerAllocator>
struct DataType< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "direct_lidar_odometry/save_trajRequest";
  }

  static const char* value(const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string save_path\n"
;
  }

  static const char* value(const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.save_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_trajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::direct_lidar_odometry::save_trajRequest_<ContainerAllocator>& v)
  {
    s << indent << "save_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.save_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJREQUEST_H
