// Generated by gencpp from file direct_lidar_odometry/save_traj.msg
// DO NOT EDIT!


#ifndef DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJ_H
#define DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJ_H

#include <ros/service_traits.h>


#include <direct_lidar_odometry/save_trajRequest.h>
#include <direct_lidar_odometry/save_trajResponse.h>


namespace direct_lidar_odometry
{

struct save_traj
{

typedef save_trajRequest Request;
typedef save_trajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_traj
} // namespace direct_lidar_odometry


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::direct_lidar_odometry::save_traj > {
  static const char* value()
  {
    return "ac67446d8a94887127d80e989a0feea9";
  }

  static const char* value(const ::direct_lidar_odometry::save_traj&) { return value(); }
};

template<>
struct DataType< ::direct_lidar_odometry::save_traj > {
  static const char* value()
  {
    return "direct_lidar_odometry/save_traj";
  }

  static const char* value(const ::direct_lidar_odometry::save_traj&) { return value(); }
};


// service_traits::MD5Sum< ::direct_lidar_odometry::save_trajRequest> should match
// service_traits::MD5Sum< ::direct_lidar_odometry::save_traj >
template<>
struct MD5Sum< ::direct_lidar_odometry::save_trajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::direct_lidar_odometry::save_traj >::value();
  }
  static const char* value(const ::direct_lidar_odometry::save_trajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::direct_lidar_odometry::save_trajRequest> should match
// service_traits::DataType< ::direct_lidar_odometry::save_traj >
template<>
struct DataType< ::direct_lidar_odometry::save_trajRequest>
{
  static const char* value()
  {
    return DataType< ::direct_lidar_odometry::save_traj >::value();
  }
  static const char* value(const ::direct_lidar_odometry::save_trajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::direct_lidar_odometry::save_trajResponse> should match
// service_traits::MD5Sum< ::direct_lidar_odometry::save_traj >
template<>
struct MD5Sum< ::direct_lidar_odometry::save_trajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::direct_lidar_odometry::save_traj >::value();
  }
  static const char* value(const ::direct_lidar_odometry::save_trajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::direct_lidar_odometry::save_trajResponse> should match
// service_traits::DataType< ::direct_lidar_odometry::save_traj >
template<>
struct DataType< ::direct_lidar_odometry::save_trajResponse>
{
  static const char* value()
  {
    return DataType< ::direct_lidar_odometry::save_traj >::value();
  }
  static const char* value(const ::direct_lidar_odometry::save_trajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJ_H
