// Generated by gencpp from file direct_lidar_odometry/save_trajResponse.msg
// DO NOT EDIT!


#ifndef DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJRESPONSE_H
#define DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace direct_lidar_odometry
{
template <class ContainerAllocator>
struct save_trajResponse_
{
  typedef save_trajResponse_<ContainerAllocator> Type;

  save_trajResponse_()
    : success(false)  {
    }
  save_trajResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> const> ConstPtr;

}; // struct save_trajResponse_

typedef ::direct_lidar_odometry::save_trajResponse_<std::allocator<void> > save_trajResponse;

typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajResponse > save_trajResponsePtr;
typedef boost::shared_ptr< ::direct_lidar_odometry::save_trajResponse const> save_trajResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator1> & lhs, const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator1> & lhs, const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace direct_lidar_odometry

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "direct_lidar_odometry/save_trajResponse";
  }

  static const char* value(const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_trajResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::direct_lidar_odometry::save_trajResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIRECT_LIDAR_ODOMETRY_MESSAGE_SAVE_TRAJRESPONSE_H
